Name: api-backend

Log:
  Level: debug
  Format: console
  Directory: ./logs
  Development: true

HTTP:
  Host: 0.0.0.0
  Port: 8080

SuperAdmin:
  Username: admin
  Realname: 슈퍼 관리자
  Password: P9661144!

Auth:
  Enable: true
  TokenExpired: 7200
  IgnorePathPrefixes:
    - /pprof
    - /swagger
    - /api/v1/publics/captcha
    - /api/v1/publics/user/login
  Captcha:
    Enable: false
    Width: 240        # 140
    Height: 80        # 46
    NoiseCount: 2     # 2

Casbin:
  Enable: true
  Debug: false
  AutoLoad: false
  AutoLoadInternal: 10
  IgnorePathPrefixes:
    - /pprof
    - /swagger
    - /api/v1/publics/user
    - /api/v1/publics/captcha

Redis:
  Host: 192.168.5.58
  Port: 6379
#  Password: aosk1101!
  KeyPrefix: r

Database:
  Engine: mysql
  Name: echo
  Host: 129.154.59.231
  Port: 13306
  Username: root
  Password: P9661144!
  TablePrefix: t
  Parameters: charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true&timeout=5s
  MaxLifetime: 7200
  MaxOpenConns: 150
  MaxIdleConns: 50
